# Generated by Django 2.2.2 on 2020-01-13 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('login', models.BooleanField(default=False)),
                ('role', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='C:\\Users\\Eric Bello\\Documents\\Python\\ipnsite\\media/profiles')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Area')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='C:\\Users\\Eric Bello\\Documents\\Python\\ipnsite\\media/documents')),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reviewed', models.BooleanField(blank=True, default=False, null=True)),
                ('published', models.BooleanField(blank=True, default=False, null=True)),
                ('visible', models.BooleanField(blank=True, default=True, null=True)),
                ('urgent', models.BooleanField(blank=True, default=False, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('addressed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.AddressedTo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Profiles')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.PublicationType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='C:\\Users\\Eric Bello\\Documents\\Python\\ipnsite\\media/images')),
                ('image_preview', models.ImageField(upload_to='C:\\Users\\Eric Bello\\Documents\\Python\\ipnsite\\media/images_preview')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Publications')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
