# Generated by Django 2.2.2 on 2019-12-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20191203_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
