# Generated by Django 2.2.2 on 2019-12-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20191203_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
