# Generated by Django 2.2.2 on 2019-12-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
