# Generated by Django 2.2.2 on 2019-12-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_profiles_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='admin',
            new_name='permission',
        ),
    ]
