# Generated by Django 2.2.2 on 2019-12-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20191209_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='permission',
        ),
    ]
