# Generated by Django 2.2.2 on 2019-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20191209_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='edition',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='revision',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
