# Generated by Django 2.2.2 on 2019-12-12 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_addressedto_publicationtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publications',
            old_name='text',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='publications',
            name='addressed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.AddressedTo'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.PublicationType'),
        ),
    ]
