# Generated by Django 2.2.2 on 2019-12-13 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20191212_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='C:\\Users\\Eric Bello\\Documents\\Python\\ipnsite\\mediaimage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='publications',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Images'),
        ),
    ]
