# Generated by Django 2.2.2 on 2019-12-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20191212_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Publications'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\Eric Bello\\Documents\\Python\\ipnsite\\media/image'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\Eric Bello\\Documents\\Python\\ipnsite\\media/profiles'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\Eric Bello\\Documents\\Python\\ipnsite\\media/documents'),
        ),
    ]
