# Generated by Django 2.2.2 on 2019-12-15 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20191213_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publications',
            old_name='edition',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='revision',
            new_name='reviewed',
        ),
    ]
