# Generated by Django 2.2.2 on 2019-12-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20191214_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressedto',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='addressedto',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publicationtype',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publicationtype',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
