# Generated by Django 2.2.2 on 2019-12-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_auto_20191215_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='visible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
