# Generated by Django 2.2.2 on 2019-12-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_publications_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
