# Generated by Django 2.2.2 on 2019-12-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_publications_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
