# Generated by Django 2.2.2 on 2020-01-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_publications_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='permission',
            new_name='role',
        ),
    ]
